services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: study
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build: .
    container_name: backend_java
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/study
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    expose:
      - "8080" # importante: não expor externamente, só pra rede interna
    restart: always
    networks:
      - app_network

  nginxproxymanager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    restart: always
    ports:
      - "80:80"      # HTTP
      - "81:81"      # Painel administrativo
      - "443:443"    # HTTPS
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
